-- Initial schema for fresh installations. Existing databases baselined at V1
-- keep their tables; Flyway only applies later migrations to those databases.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255) NOT NULL CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    category VARCHAR(255) CHECK (category IN (
        'PLUMBING', 'ELECTRICAL', 'CLEANING', 'HEATING', 'GARDENING', 'APPLIANCE_REPAIR'
    ))
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_date DATE,
    booking_time TIME(6),
    address VARCHAR(255),
    status VARCHAR(255) CHECK (status IN ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED')),
    user_id BIGINT REFERENCES users(id),
    service_id BIGINT REFERENCES services(id)
);
